version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
            - redis
        networks:
            - default
    